# Generated by Django 3.2.5 on 2021-07-03 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^\\01?\\d{9}$')])),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('governament', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
