# Generated by Django 3.2.5 on 2021-07-03 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_phone_number'),
        ('hero', '0002_alter_hero_phone_number'),
        ('api', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.hero')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.hero')),
            ],
        ),
    ]
