# Generated by Django 3.2.5 on 2021-07-03 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_acceptedrequest_hiringrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedrequest',
            old_name='user_id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='hiringrequest',
            old_name='user_id',
            new_name='client_id',
        ),
    ]
